import "~/styles/globals.css";

import {GeistSans} from "geist/font/sans";
import {type Metadata} from "next";

import {ClerkProvider} from "@clerk/nextjs"
import {Topnav} from "./_components/topnav";


export const metadata: Metadata = {
  title: "Baba t",
  description: "Generated by Urvish Patel",
  icons: [{rel: "icon", url: "/favicon.ico"}],
};


export default function RootLayout({
                                     children,
                                   }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>

      <html lang="en" className={`font-sans ${GeistSans.variable} flex flex-col gap-4`}>
      <body>
      <Topnav/>
      {children}
      </body>
      </html>

    </ClerkProvider>
  );
}
